import { UserProvider } from "@/context/user/userProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function ModulesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
